### ISSUE TITLE
Add option to include relative links

### ISSUE THREAD

**Issue by vlad-zhukov** [rehypejs/rehype-external-links#11]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

I'd like to use this plugin to add `target` and `rel` properties to links with relative urls. [Currently only absolute urls are supported.](https://github.com/rehypejs/rehype-external-links/blob/b0ada86b178e135d55368ffa47b915db17219716/lib/index.js#L123:L125)

### Solution

I suggest the `test` option to be responsible for that. By default it filters links with absolute urls, and you can override it. This is a breaking change.

### Alternatives

- Add a new option `includeRelative`
- Remove filtering completely

**Comment by wooorm** [comment]
Your use case sounds unrelated to this project. This project is explicitly called “external links”, and is about making them safe.
What `rel`s and `target` do you want to add?
I’d probably recommend to make your own plugin. That’s what our entire ecosystem is about: that you can write plugins to do anything. You likely don’t need much of the logic here. You’ll have simpler code, a smaller bundler, and better performance

**Comment by vlad-zhukov** [comment]
I just want certain links to open in a new tab. My own plugin might be a better option here. Thanks!
