### ISSUE TITLE
feat: exclude certain links with a `no-external` attribute

### ISSUE THREAD

**Issue by okikio** [rehypejs/rehype-external-links#3]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Right now all external links get targeted but there are instances where users may want to exclude a specific link. 

In my use case, I use `rehype-external-links` for all externals links, I then attach an icon to the external links to indicate that the link takes the user out of the page. 

The problem comes when attaching an external link to images, an extra icon appears messing up layout. In my use case being able to exclude links individually would go a long way.

### Solution

* Add the option to use an attribute to exclude links individually

### Alternatives

* Exclude links that have images as the primary content
* I can't think of any other alternatives that aren't awkward to use or implement.

Thanks for creating this plugin.

**Comment by wooorm** [comment]
Hey!

> Add the option to use an attribute to exclude links individually

What do you propose?

> Exclude links that have images as the primary content

There may be something to be said for this, but I can imagine not everyone wanting it, and it would be a breaking change.

> I can't think of any other alternatives that aren't awkward to use or implement.

What if there’s an `options.test`, that could be a function, so that you can choose that attribute yourself?

**Comment by wooorm** [comment]
And, would these ignored links still get things like `target`, `rel`, etc? Just no icon?
If so, maybe `options.content` could be a function, that receives the current node, and then you could return nothing for these links with images, or return your content for links without images?

**Comment by okikio** [comment]
Both of these would work, maybe even making the target and rel attributes a function as well so peeps can change the target and rel depending on the element.

**Comment by wooorm** [comment]
Is this something you could work on?

**Comment by okikio** [comment]
I'll try to

**Comment by wooorm** [comment]
I think as mentioned an `options.test` function could now do this.
Similar to:
- https://github.com/rehypejs/rehype-autolink-headings#optionstest
- https://github.com/rehypejs/rehype-autolink-headings/blob/a37d231c4c0c29c6880d8e1b6842dfbd771027dc/lib/index.js#L62
- https://github.com/rehypejs/rehype-autolink-headings/blob/a37d231c4c0c29c6880d8e1b6842dfbd771027dc/lib/index.js#L84

**Comment by wooorm** [comment]
Closing as an issue. I think a PR that adds the feature as outlined above is acceptable!

**Comment by okikio** [comment]
Sorry about this, I just haven't had time to add support for attributes. Thanks for all your help though

**Comment by wooorm** [comment]
No problem! :)

**Comment by ShivamJoker** [comment]
@wooorm I am unable to figure out how to exclude my domain links from having `rel=nofollow`

Can you please help me out?

**Comment by ShivamJoker** [comment]
I managed to do it like this 

```js
          rel: (el) => {
            if (!el.properties.href.includes("learnaws.io")) {
              return ["nofollow"];
            }
            return [];
          },
```

**Comment by wooorm** [comment]
Please see the above discussion. To summarize: this isn’t implemented. PR welcome to add a test.

**Comment by ShivamJoker** [comment]
> Please see the above discussion. To summarize: this isn’t implemented. PR welcome to add a test.

I am not sure what you meant by adding test

**Comment by wooorm** [comment]
See https://github.com/rehypejs/rehype-external-links/issues/3#issuecomment-1179710091

**Comment by hanneskuettner** [comment]
To tag onto this (and submit a PR once this is discussed). Would you rather introduce a test option identical to the one you linked where the test is passed to `hast-util-is-element` or a simple option that can either be a RegEx or a function that receives the URL as its only argument?

I guess a test that is passed to `hast-util-is-element` is more canonical, but most of the possible parameter types are unused (only `TestFunction*` would make sense since we only ever visit `a` elements anyways.

Any input so I could drop a PR?

**Comment by wooorm** [comment]
Hi Hannes! Good points.
I think it’s easier to understand if the same test mechanism is supported here and in other places, so, `hast-util-is-element`.
I’d imagine that a simple function will become less simple later on, getting more stuff added to it. While `hast-util-is-element` already does all that.
Even though some parts of `hast-util-is-element` will not be useful here.
