### ISSUE TITLE
The package in npm is not same with Github

### ISSUE THREAD

**Issue by ForXd** [rehypejs/rehype-external-links#7]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

The package in npm is not same with Github， npm package can't support dynamic target。

### Solution

publish latest version to npm

### Alternatives

。

**Comment by wooorm** [comment]
Yes, we are working towards a release.

**Comment by BeauAgst** [comment]
Thanks @wooorm, when do you think this release will go out?

**Comment by wooorm** [comment]
Just cut a release for [v2](https://github.com/rehypejs/rehype-external-links/releases/tag/2.0.0).
